---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kubecost
  namespace: kubecost
spec:
  hosts:
    - "billing.{{ .Values.domain }}"
  gateways:
    - kubecost 
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: "kubecost-cost-analyzer"
            port:
              number: 9090